=== whoiam-bat/TheBookSpot-InternetBookStore/src/main/webapp/xml/books.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.nure.ua"
           xmlns="http://www.nure.ua"
           elementFormDefault="qualified">
    <xs:element name="bookList">
        <xs:complexType>
            <xs:sequence>

                <xs:element name="book" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value=".+"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== whoiam-bat/TheBookSpot-InternetBookStore/src/main/webapp/xml/books-out.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<bookList xmlns="http://www.nure.ua" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.nure.ua file:///D:/My-Folder/Programming/Java/EPAM/Final-Project/InternetStore/store/src/main/webapp/xml/books.xsd">
    <book>
        <title>1984</title>
    </book>
    <book>
        <title>Animal Farm</title>
    </book>
    <book>
        <title>Harry Potter and the Philosopher's Stone</title>
    </book>
    <book>
        <title>Harry Potter and the Chamber of Secrets</title>
    </book>
    <book>
        <title>Harry Potter and the Prisoner of Azkaban</title>
    </book>
    <book>
        <title>Harry Potter and the Goblet of Fire</title>
    </book>
    <book>
        <title>Harry Potter and the Order of the Phoenix</title>
    </book>
    <book>
        <title>Harry Potter and the Half-Blood Prince</title>
    </book>
    <book>
        <title>Harry Potter and the Deathly Hallows</title>
    </book>
    <book>
        <title>A Game of Thrones</title>
    </book>
    <book>
        <title>A Clash of Kings</title>
    </book>
    <book>
        <title>A Storm of Swords</title>
    </book>
    <book>
        <title>A Feast for Crows</title>
    </book>
    <book>
        <title>A Dance with Dragons</title>
    </book>
    <book>
        <title>Norse Mythology</title>
    </book>
</bookList>
